apiVersion: troubleshoot.sh/v1beta2
kind: Preflight
metadata:
  name: cluster-is-minikube
  annotations:
    title: "Check if minikube kubernetes cluster"
    description: "Verify that the Kubernetes cluster is minikube"
    category: "embedded_cluster"
    iconUri: "/category-icons/kubernetes.svg"
    tags: '["kubernetes", "embedded-cluster"]'
    contributors: '[{"name": "Evans Mungai", "avatarUri": "https://avatars.githubusercontent.com/u/681087?v=4"}]'
spec:
  collectors: []
  analyzers:
    - distribution:
        outcomes:
          - pass:
              when: "== minikube"
              message: minikube is a supported distribution
          - warn:
              message: The cluster is not running on minikube
