#!/bin/sh
YARN_CACHE="./node_modules/yarn-cache"

mkdir -p "$YARN_CACHE"

cache_deps() {
    PACKAGES=$@

    for PKG in $PACKAGES
    do
        PKG_NODE_MODULES="./$PKG/node_modules"
        if [ -d $PKG_NODE_MODULES ];
        then
            mv $PKG_NODE_MODULES $YARN_CACHE/$PKG
            echo "Cached node modules for $PKG"
        else
            echo "Unable to cache node modules for $PKG"
        fi
    done
}

cache_deps `jq -r '.workspaces|join(" ")' < package.json`
