#!/bin/sh
for WORKSPACE in $@
do
    if [ -d "$WORKSPACE/.cache" ]; then
        mv "$WORKSPACE/.cache" ".cache/$WORKSPACE"
        echo "Saved cache for $WORKSPACE"
    else
        echo "Unable to save cache for $WORKSPACE"
    fi
done
